version: '2'
services:
  vnuaserver-app:
    image: vnuaserver
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://vnuaserver-postgresql:5432/vnuaServer
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://vnuaserver-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://vnuaserver-elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - 8080:8080
  vnuaserver-postgresql:
    extends:
      file: postgresql.yml
      service: vnuaserver-postgresql
  vnuaserver-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: vnuaserver-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
